// Automatically generated by astro-icon
// 0a12f86b1158a8cddce111245fd7e8a0d2e92cda37edd13f72e8064e9c0dcf21

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "arrow-left"
		| "arrow-up-right-bold"
		| "copy"
		| "github"
		| "instagram"
		| "linkedin"
		| "threads"
		| "twitch"
		| "x"
		| "youtube";
}